package com.contextguard.app.ui.viewmodel

data class ReadyDemoScenario(
    val id: String,
    val number: Int,
    val title: String,
    val tag: String,
    val artifactName: String,
    val sourceApp: String,
    val action: String,
    val recipient: String,
    val destination: String,
    val expectedIntervention: InterventionType,
    val severity: Float,
    val irreversibility: Float,
    val confidence: Float,
    val description: String,
    val evidenceList: List<String>,
    val rationale: String,
    val alternativeAction: String,
    val urlRiskScore: Float? = null,
    val ocrSnippet: String? = null
)

val ReadyDemoScenariosList = listOf(
    ReadyDemoScenario(
        id = "DEMO_BANK_STATEMENT",
        number = 1,
        title = "Bank statement",
        tag = "Financial PDF",
        artifactName = "HDFC_Bank_Statement_Oct2026.pdf",
        sourceApp = "HDFC Mobile Banking",
        action = "POST",
        recipient = "Public Feed",
        destination = "Public Twitter/X Feed",
        expectedIntervention = InterventionType.STOP,
        severity = 0.90f,
        irreversibility = 1.00f,
        confidence = 0.95f,
        description = "Unredacted financial transaction history posted to a publicly indexed timeline.",
        evidenceList = listOf(
            "OCR identified Account No: 4532 0150 1234 5671 and IFSC: HDFC0000128",
            "Target destination is public social timeline with permanent indexing",
            "Action POST executes irrevocable global disclosure hazard (r = 1.00)",
            "Policy evaluated: rho = 0.90 * (1 + 0.75 * 1.00) = 1.575 (STOP threshold >= 0.65)"
        ),
        rationale = "Permanent public broadcast of financial PII causes catastrophic irreversible harm. Action blocked to prevent identity theft.",
        alternativeAction = "Mask sensitive account numbers and save to encrypted personal vault instead.",
        ocrSnippet = "HDFC BANK LIMITED\nAccount No: 4532 0150 1234 5671\nAvailable Balance: INR 1,48,290.40"
    ),
    ReadyDemoScenario(
        id = "DEMO_FAKE_KYC",
        number = 2,
        title = "Fake KYC link",
        tag = "Phishing URL",
        artifactName = "http://kyc-update-sbi-portal-verify.support-desk91.net/auth",
        sourceApp = "SMS Messenger",
        action = "LOGIN",
        recipient = "Spoofed Banking Portal",
        destination = "support-desk91.net (Spoofed Portal)",
        expectedIntervention = InterventionType.STOP,
        severity = 0.95f,
        irreversibility = 0.90f,
        confidence = 0.98f,
        description = "Deceptive domain mimicking SBI netbanking attempting to harvest online banking credentials.",
        evidenceList = listOf(
            "XGBoost URL Model evaluated P(phishing) = 0.974 with high-entropy token structure",
            "Target domain registered 2 days ago without SSL EV certificate",
            "Attempted action is credential entry (LOGIN) on deceptive host",
            "Policy evaluated: rho = 0.95 * (1 + 0.75 * 0.90) = 1.591 (STOP threshold >= 0.65)"
        ),
        rationale = "Target URL matches known phishing heuristics. Action LOGIN directly exposes credentials to malicious actors.",
        alternativeAction = "Discard message and navigate to official banking app directly.",
        urlRiskScore = 0.974f
    ),
    ReadyDemoScenario(
        id = "DEMO_OTP_SCREENSHOT",
        number = 3,
        title = "OTP screenshot",
        tag = "System Screenshot",
        artifactName = "Screenshot_2026-10-06_Aadhaar_OTP.png",
        sourceApp = "System Screenshot",
        action = "SEND",
        recipient = "Customer Support (@support_bot)",
        destination = "Unverified Telegram Contact",
        expectedIntervention = InterventionType.STOP,
        severity = 0.95f,
        irreversibility = 1.00f,
        confidence = 0.99f,
        description = "Screenshot showing a 6-digit Aadhaar UIDAI authentication OTP transmitted to an unverified chat contact.",
        evidenceList = listOf(
            "ML Kit OCR detected 6-digit one-time passcode: '482910' with expiry alert",
            "Destination is third-party unverified chat contact",
            "Transmitting live authentication OTP causes immediate account hijacking",
            "Policy evaluated: rho = 0.95 * (1 + 0.75 * 1.00) = 1.662 (STOP threshold >= 0.65)"
        ),
        rationale = "Sharing ephemeral authentication secrets (OTP) to third-party chat enables immediate session takeover.",
        alternativeAction = "Never share OTP with anyone. ContextGuard has blacked out the OTP code.",
        ocrSnippet = "Aadhaar Verification Code: 482910\nValid for 10 minutes. Do not share with anyone."
    ),
    ReadyDemoScenario(
        id = "DEMO_UNKNOWN_RECIPIENT",
        number = 4,
        title = "Unknown recipient document",
        tag = "Confidential Doc",
        artifactName = "Confidential_Q3_Financial_Audit.docx",
        sourceApp = "Corporate Drive",
        action = "SEND",
        recipient = "external-auditor-99@temp-mail.org",
        destination = "external-auditor-99@temp-mail.org",
        expectedIntervention = InterventionType.ASK,
        severity = 0.60f,
        irreversibility = 0.70f,
        confidence = 0.55f,
        description = "Internal financial audit transmitted to an unverified disposable email address, triggering epistemic uncertainty gating.",
        evidenceList = listOf(
            "Recipient email domain uses disposable mail service (@temp-mail.org)",
            "Document contains corporate internal revenue and liability audit",
            "Epistemic confidence c = 0.55 (< 0.70 threshold) triggers ASK gating protocol",
            "Policy evaluated: rho = 0.60 * (1 + 0.75 * 0.70) = 0.915 with high uncertainty"
        ),
        rationale = "High epistemic uncertainty regarding recipient identity. Clarification required before transmitting business audit.",
        alternativeAction = "Verify recipient email address through official corporate directory before sending.",
        ocrSnippet = "CONFIDENTIAL AUDIT REPORT Q3\nTotal Revenue: $4,200,000\nInternal Distribution Only"
    ),
    ReadyDemoScenario(
        id = "DEMO_ROUTINE_PHOTO",
        number = 5,
        title = "Routine family photo",
        tag = "Personal Photo",
        artifactName = "Family_Vacation_Diwali.jpg",
        sourceApp = "Gallery",
        action = "POST",
        recipient = "Instagram Followers",
        destination = "Instagram Feed",
        expectedIntervention = InterventionType.ACT,
        severity = 0.10f,
        irreversibility = 0.20f,
        confidence = 0.95f,
        description = "Standard personal vacation photograph with no detected credentials, PII, financial details, or sensitive metadata.",
        evidenceList = listOf(
            "ML Kit detected 0 sensitive PII entities",
            "Face detection verified non-restricted personal photography",
            "Risk score rho = 0.115 is well below 0.35 threshold",
            "Policy evaluated: rho = 0.10 * (1 + 0.75 * 0.20) = 0.115 (ACT safe zone)"
        ),
        rationale = "Routine personal photo without detected credentials or sensitive PII. Safe to proceed.",
        alternativeAction = "None required. Safe to proceed."
    ),
    ReadyDemoScenario(
        id = "DEMO_ROUTINE_NEWS",
        number = 6,
        title = "Routine news URL",
        tag = "Verified Link",
        artifactName = "https://www.reuters.com/technology/ai-advancements-2026",
        sourceApp = "Chrome Browser",
        action = "OPEN",
        recipient = "Colleague Group Chat",
        destination = "Colleague Group Chat",
        expectedIntervention = InterventionType.ACT,
        severity = 0.05f,
        irreversibility = 0.00f,
        confidence = 0.98f,
        description = "Reputable global journalism website with clean SSL certificate, low token entropy, and verified domain authority.",
        evidenceList = listOf(
            "XGBoost URL Model evaluated P(phishing) = 0.008 (Legitimate)",
            "Domain authority: Reuters News Service (established reputation)",
            "Clean lexical and structural profile",
            "Policy evaluated: rho = 0.05 * (1 + 0.75 * 0.00) = 0.050 (ACT safe zone)"
        ),
        rationale = "Verified legitimate news URL with reputable domain authority. No risk detected.",
        alternativeAction = "None required. Safe to proceed.",
        urlRiskScore = 0.008f
    ),
    ReadyDemoScenario(
        id = "DEMO_CONTRACT_LOCKIN",
        number = 7,
        title = "Contract lock-in",
        tag = "Vendor Contract",
        artifactName = "Cloud_SaaS_Enterprise_Agreement_v3.pdf",
        sourceApp = "DocuSign",
        action = "SIGN",
        recipient = "Enterprise SaaS Vendor",
        destination = "Vendor DocuSign Envelope",
        expectedIntervention = InterventionType.WARN,
        severity = 0.55f,
        irreversibility = 0.85f,
        confidence = 0.88f,
        description = "Enterprise agreement containing automatic 36-month renewal lock-in with 90-day cancellation window and liquidated damages.",
        evidenceList = listOf(
            "OCR detected clause 14.2: 'Auto-renews for consecutive 36-month terms'",
            "Early termination subject to 100% remaining contract liability penalty",
            "Action SIGN commits legally binding corporate obligations",
            "Policy evaluated: rho = 0.55 * (1 + 0.75 * 0.85) = 0.901 (WARN zone)"
        ),
        rationale = "Contractual lock-in detected. Document contains aggressive 3-year auto-renewal and termination penalties.",
        alternativeAction = "Request removal of auto-renewal clause 14.2 or reduce term length prior to signing.",
        ocrSnippet = "Section 14.2 Term and Renewal: This Agreement shall automatically renew for additional 36-month terms unless 90 days notice..."
    ),
    ReadyDemoScenario(
        id = "DEMO_PAYMENT_REQUEST",
        number = 8,
        title = "Payment request",
        tag = "Invoice Image",
        artifactName = "Invoice_Payable_Urgent_Transfer.png",
        sourceApp = "Outlook Mail",
        action = "APPROVE",
        recipient = "New Bank Beneficiary Account",
        destination = "Payment Gateway / Wire",
        expectedIntervention = InterventionType.WARN,
        severity = 0.70f,
        irreversibility = 0.90f,
        confidence = 0.65f,
        description = "Urgent vendor invoice containing recently modified bank account details, exhibiting business email compromise (BEC) traits.",
        evidenceList = listOf(
            "Urgency indicators detected: 'Immediate Transfer Required Within 2 Hours'",
            "Beneficiary bank account changed from historical vendor record",
            "Epistemic confidence c = 0.65 indicates heightened payment diversion risk",
            "Policy evaluated: rho = 0.70 * (1 + 0.75 * 0.90) = 1.172 (WARN checkpoint)"
        ),
        rationale = "Urgent payment request with recently modified banking details. Potential executive impersonation or BEC fraud.",
        alternativeAction = "Initiate out-of-band telephone verification with vendor accounting team before approval.",
        ocrSnippet = "INVOICE #9812 - URGENT PAYMENT NOTICE\nAmount Due: INR 2,45,000\n*NEW* Bank Account Details Listed Below"
    )
)
